
[phases.setup]
	"nodejs",
	"python3",
	"chromium",
	"glib",
	"nss",
	"atk",
	"cups",
	"pango",
	"libxcomposite",
	"libxdamage",
	"libxrandr",
	"libgbm",
	"libasound",
	"libxshmfence",
	"libxinerama",
	"libxext",
	"libxfixes",
	"libxi",
	"libxtst",
	"ca-certificates",
	"fonts-liberation",
	"libappindicator-gtk3",
	"libdrm",
	"libdbusmenu",
	"libgtk-3"
]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "node backend/src/index.js"
